### ISSUE TITLE
Make badge value configurable

### ISSUE THREAD

**Issue by emkman** [unspentio/ethereum-gas-prices-browser-extension#1]
It would be great to have the option to set which category the badge shows. I would like to be able to set the badge Fast instead of Normal for instance. This data is most important because it can be seen with no clicks while using an open Metamask window.

Bonus points for allowing a configurable offset, i.e. show Normal + 5 gwei, since relying on normal is often not enough while gas prices are rapidly rising.

**Comment by pioul** [comment]
Hi! The ability to choose which speed & which price provider to show in the badge is a great suggestion, one I was sure would come up at some point :)

About a configurable offset, I do see the value in this, and wonder how many people always use the exact same offset versus using variable offsets based on all the price estimations seen at the moment (e.g. if high volatility in gas prices, and prices trending higher, a large offset might be a good idea). All that to say that I'd love to build a clearer understanding about how many different people take into account those price estimations to pick the right gas price for them – and when a common theme emerges, adding it to the extension will totally make sense! For now I'm taking note of how you're using those estimations and will keep my ears open to learn about how others do.


Back to the option to choose which speed & provider to display in the badge: I just added it! The updated extensions are being reviewed by Google and Mozilla, so the update should reach you within a few hours :) It looks like this:

![image](https://user-images.githubusercontent.com/2307365/93596763-37958300-f9ba-11ea-8ece-6c1e5c704174.png)

Cheers, thanks for those suggestions, let me know if you have any others!
